##------------------CARLA server config------------------##
carla_server:
  host: 'localhost'
  timeout: 2.0
  timestep: 0.1
  retries_on_error: 25
  resolution_x: 600
  resolution_y: 600
  quality_level: 'Low'
  enable_map_assets: False
  enable_rendering: False
  show_display: False
  carla_path: '/home/hemanth/Carla/CARLA_0.9.11'
  debug: True

##------------------Experiment config------------------##
available_weathers: [
    'MidRainSunset', # Done
    'ClearNoon', # Done
    'SoftRainNoon', # Done
    'HardRainNoon', # Testing (Done)
    'ClearSunset', # Testing (not done)
    'SoftRainSunset', # Done
    'HardRainSunset', # Testing
  ]
experiment:
  weather:
    [
      'HardRainSunset',
      'ClearNoon',
      'SoftRainNoon',
      'SoftRainSunset',
      'HardRainNoon',
    ]
  background_activity:
    n_vehicles: 50
    n_walkers: 20
    tm_hybrid_mode: True
    seed: null
  town: 'Town01'
  navigation_type: ['navigation'] # 'straight'

##------------------Vehicle config------------------##
vehicle:
  target_speed: 20 # Km/hr
  ignore_traffic_lights: False
  agent: 'Behavior'
  behavior: ['cautious'] #  'cautious', 'aggressive'
  blueprint: 'vehicle.lincoln.mkz2017'
  sensors:
    collision:
      type: 'sensor.other.collision'
    imu:
      type: 'sensor.other.imu'
    gnss:
      type: 'sensor.other.gnss'
    obstacle:
      type: 'sensor.other.obstacle'
      distance: 5
      hit_radius: 0.5
      only_dynamics: True
    semseg:
      type: 'sensor.camera.semantic_segmentation'
      image_size_x: 256
      image_size_y: 256
      transform: '1.25,0,1.85,-90,0,0'
    rgb:
      type: 'sensor.camera.rgb'
      image_size_x: 256
      image_size_y: 256
      transform: '1.25,0,1.85,-90,0,0'
  sensors_process:
    normalized: True
    gray_scale: True
  spawn_points: []

##------------------Datawriter config------------------##
data_writer:
  shard_write: True
  shard_maxcount: 6250
  data_write_freq: 3

##------------------Collector config------------------##
collector:
  steps: 150000
  data_write_path: '../../../Desktop/carla_data/Town01_NAVIGATION/'
  parallel_collect: True
  number_collectors: 3

##------------------Collector config------------------##
reader:
  data_read_path: '../../../Desktop/carla_data/Town01_NAVIGATION/straight/'
  create_movie: True

##------------------Simulation config------------------##
simulation:
  seed: 1337
  sync: True
# ../../../Desktop/CIRL Pace Cluster/carla-imitation-learning/data/raw/
